import React, { useState, useEffect } from 'react';
import css from './About.module.css';

function About() {
  const [text, setText] = useState("Ваш текст");
  const [position, setPosition] = useState(0);
  const [direction, setDirection] = useState("left");

  useEffect(() => {
    const interval = setInterval(() => {
      if (direction === "left") {
        setPosition(prevPosition => prevPosition + 1);
        if (position >= window.innerWidth) {
          setDirection("right");
        }
      } else {
        setPosition(prevPosition => prevPosition - 1);
        if (position <= 0) {
          setDirection("left");
        }
      }
    }, 50);

    return () => clearInterval(interval);
  }, [direction, position]);

  const textStyle = {
    transform: `translateX(${position}px)`,
    color: 'white',
  };
  return (
    <>
      <h2 className={css.introText}>a Story that <br /> started <br /> with <span className={css.pinkText}>one <br /> simple</span> <br /> <span className={css.pinkText}>ape</span></h2>
      <h3 className={css.introText2}>WHO GOT <br /> FED UP WITH BORING <br /> AND HYPOCRITIC <br /> COMMONPLACE THIS IS <br /> HOW THE IDEA OF <br /> ESCAPING AND DYNAMIC <br /> JOURNEY ON THE YACHT</h3>
      <ul className={css.aboutList}>
        <li><div>X</div></li>
        <li><p>EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE RANDOMLY GENERATED BY USERS</p></li>
      </ul>
      <img className={css.photo} src="https://s3-alpha-sig.figma.com/img/79d5/45ad/e4c8bc4d1e7b7145ae4fa160aa45374d?Expires=1711929600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=iQ2skbTdN4LqZCmgLHGjuffLh4SeEEZsa0q0vS1MOLqxfAts8diybK5lU0mdaKdV95e2q4Wa1CL-Pat--hL3y6lRtUhPnbGiaCSCWwM0eaqDUDDFnR-umDnl2eIOpjt9xr-UacBp-cO~CX1J9eFrNBcVV1JjsY97KCxj9BeUXEnJNXgJCzMGAW0~tJZ6Nm3j6oLipynijyWMSF0EHWcubtkGquhieCPCq8a-8HB6gxzy5uWjH77qT8zFX4jq3uCLT0rYMVNH0YOh~IwZ52tMMKwrEXxVF~ZtLbiQjL6cls-q6JJi8FD5qW1VsAzWEESKY29NqtS46KKZEt6ZCOCTlQ__" alt="ape" /><br />
      <div>
        <h1 style={textStyle}>{text}</h1>
      </div>
    </>
  )
};

export default About;