import React from 'react';
import css from './about.module.css';

function About() {
  return (
    <>
      <div className={css.aboutText}>
        <h2 className={css.introText}>A STORY THAT <br /> STARTED <br /> WITH <span className={css.pinkText}>ONE <br /> SIMPLE</span> <br /> <span className={css.pinkText}>APE</span></h2>
        <h3 className={css.introText2}>WHO GOT <br /> FED UP WITH BORING <br /> AND HYPOCRITIC <br /> COMMONPLACE THIS IS <br /> HOW THE IDEA OF <br /> ESCAPING AND DYNAMIC <br /> JOURNEY ON THE YACHT</h3>
      </div>
      <div className={css.aboutPhoto}>
        <ul className={css.aboutList}>
          <li><div>X</div></li>
          <li><p>EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE RANDOMLY GENERATED BY USERS</p></li>
        </ul>
        <img className={css.photo} src="https://s3-alpha-sig.figma.com/img/79d5/45ad/e4c8bc4d1e7b7145ae4fa160aa45374d?Expires=1711929600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=iQ2skbTdN4LqZCmgLHGjuffLh4SeEEZsa0q0vS1MOLqxfAts8diybK5lU0mdaKdV95e2q4Wa1CL-Pat--hL3y6lRtUhPnbGiaCSCWwM0eaqDUDDFnR-umDnl2eIOpjt9xr-UacBp-cO~CX1J9eFrNBcVV1JjsY97KCxj9BeUXEnJNXgJCzMGAW0~tJZ6Nm3j6oLipynijyWMSF0EHWcubtkGquhieCPCq8a-8HB6gxzy5uWjH77qT8zFX4jq3uCLT0rYMVNH0YOh~IwZ52tMMKwrEXxVF~ZtLbiQjL6cls-q6JJi8FD5qW1VsAzWEESKY29NqtS46KKZEt6ZCOCTlQ__" alt="ape" /><br />
      </div>
      <div className={css.banner}><p>DESTROY STEREOTYPES</p> x <p>HAVE NO LIMITS</p> x <p>BREAK RULES</p></div>
    </>
  )
};

export default About;